# Generated by Django 4.1 on 2022-08-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mycustomuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mycustomuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
