# Generated by Django 4.1 on 2022-08-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_mycustomuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mycustomuser",
            name="city",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
