# Generated by Django 4.1 on 2022-08-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_mycustomuser_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="mycustomuser",
            name="slug",
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
