# Generated by Django 4.1 on 2022-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_mycustomuser_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mycustomuser",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
