# Generated by Django 4.1 on 2022-08-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_mycustomuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mycustomuser",
            name="random_identifier",
            field=models.SmallIntegerField(default=25555),
        ),
        migrations.AlterField(
            model_name="mycustomuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
