# Generated by Django 4.1 on 2022-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_mycustomuser_random_identifier_alter_mycustomuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mycustomuser",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="mycustomuser",
            name="random_identifier",
            field=models.SmallIntegerField(default=5755, unique=True),
        ),
    ]
