# Generated by Django 4.1 on 2022-08-16 07:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_mycustomuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mycustomuser",
            name="random_identifier",
            field=models.SmallIntegerField(
                default=accounts.models.create_random_identifier, unique=True
            ),
        ),
    ]
