# Generated by Django 4.1 on 2022-08-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_mycustomuser_random_identifier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mycustomuser",
            options={"verbose_name_plural": "Users"},
        ),
    ]
