# Generated by Django 4.1 on 2022-08-17 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_visits",
                    models.SmallIntegerField(verbose_name="Number of visits so far"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "New Customer"),
                            ("R", "Regular Customer"),
                            ("S", "Super Customer"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "joined",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date when customer joined"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
