# Generated by Django 4.1 on 2022-08-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "main_text",
                    models.TextField(max_length=2000, verbose_name="message content"),
                ),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("provided_on", models.DateField(auto_now_add=True)),
                ("edited_on", models.DateField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        default="Anonymous",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.customerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "main_text",
                    models.TextField(max_length=2000, verbose_name="message content"),
                ),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("provided_on", models.DateField(auto_now_add=True)),
                ("edited_on", models.DateField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        default="Anonymous",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
