# Generated by Django 4.1 on 2022-08-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="end_date",
            field=models.DateField(
                help_text="Last day of your stay/departure", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_date",
            field=models.DateField(help_text="Beginning of your stay", null=True),
        ),
    ]
