# Generated by Django 4.1 on 2022-08-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_customerprofile_total_visits"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="first_name",
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="surname",
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
