# Generated by Django 4.1 on 2022-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_reservation_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Reservation confirmed"),
                    (0, "Reservation not confirmed"),
                    (9, "Reservation is cancelled"),
                    (99, "Reservation is completed"),
                ],
                default=0,
            ),
        ),
    ]
