# Generated by Django 4.1 on 2022-08-23 14:57

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0002_suggestion_reservation_opinion"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinion",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="opinion",
            name="surname",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="opinion",
            name="author",
            field=models.ForeignKey(
                default=bookings.models.get_sentinel_user,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="author",
            field=models.ForeignKey(
                default=bookings.models.get_sentinel_user,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
