# Generated by Django 4.1 on 2022-09-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_reservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="challethouse",
            name="address",
            field=models.CharField(default="Test Address 41-200", max_length=120),
        ),
        migrations.CreateModel(
            name="ConfirmationOfReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.reservation",
                    ),
                ),
            ],
        ),
    ]
