# Generated by Django 4.1 on 2022-09-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_confirmationofreservation_saved_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConfirmationOfReservation",
            new_name="ReservationConfrimation",
        ),
    ]
