# Generated by Django 4.1 on 2022-09-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_rename_confirmationofreservation_reservationconfrimation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationconfrimation",
            name="saved_file",
            field=models.FileField(null=True, upload_to="confirmations/"),
        ),
    ]
