# Generated by Django 4.1 on 2022-09-27 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_reservationconfrimation_saved_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="opinion",
            name="rank",
            field=models.SmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(limit_value=5),
                    django.core.validators.MinValueValidator(limit_value=1),
                ],
            ),
        ),
    ]
