# Generated by Django 4.1 on 2022-09-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_alter_reservation_options_opinion_rank"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opinion",
            old_name="rank",
            new_name="rating",
        ),
    ]
